In [1]:
import pandas as pd
import numpy as np

In [2]:
# Data for COVID 
COVIDdata = pd.read_csv("COVIDdata_Racial.csv")
    
COVIDdata.shape
COVIDdata.head()

,Date,State,Cases_Total,Cases_White,Cases_Black,Cases_Latinx,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Multiracial,...,Tests_Latinx,Tests_Asian,Tests_AIAN,Tests_NHPI,Tests_Multiracial,Tests_Other,Tests_Unknown,Tests_Ethnicity_Hispanic,Tests_Ethnicity_NonHispanic,Tests_Ethnicity_Unknown
0,20210307,AK,59332.0,18300.0,1499.0,NaN,2447.0,12238.0,1508.0,4453.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20210307,AL,499819.0,160347.0,82790.0,NaN,2273.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20210307,AR,324818.0,207596.0,50842.0,NaN,2913.0,1070.0,3358.0,1804.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20210307,AS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20210307,AZ,826454.0,308453.0,25775.0,244539.0,11921.0,40707.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
extractData = COVIDdata[["Date", "State", "Cases_Total", 'Cases_White', 'Cases_Black', 'Cases_Asian', 
                         'Cases_AIAN', 'Cases_Ethnicity_Hispanic',
                        "Deaths_Total", 'Deaths_White', 'Deaths_Black', 'Deaths_Asian', 
                         'Deaths_AIAN', 'Deaths_Ethnicity_Hispanic']]

# extract most recent date for 56 states
extractData = extractData.iloc[0:56]
print(extractData.shape)

extractData

(56, 14)

,Date,State,Cases_Total,Cases_White,Cases_Black,Cases_Asian,Cases_AIAN,Cases_Ethnicity_Hispanic,Deaths_Total,Deaths_White,Deaths_Black,Deaths_Asian,Deaths_AIAN,Deaths_Ethnicity_Hispanic
0,20210307,AK,59332.0,18300.0,1499.0,2447.0,12238.0,3197.0,305.0,127.0,9.0,29.0,111.0,13.0
1,20210307,AL,499819.0,160347.0,82790.0,2273.0,NaN,12312.0,10148.0,4730.0,2223.0,24.0,NaN,137.0
2,20210307,AR,324818.0,207596.0,50842.0,2913.0,1070.0,34332.0,5319.0,4171.0,784.0,36.0,18.0,186.0
3,20210307,AS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20210307,AZ,826454.0,308453.0,25775.0,11921.0,40707.0,244539.0,16328.0,8066.0,433.0,220.0,1361.0,4684.0
5,20210307,CA,3501394.0,546630.0,111279.0,186562.0,9025.0,1509103.0,54124.0,16586.0,3275.0,6105.0,184.0,24402.0
6,20210307,CO,435762.0,181669.0,12637.0,6406.0,2527.0,119224.0,5986.0,3869.0,191.0,115.0,37.0,1204.0
7,20210307,CT,285330.0,85469.0,19651.0,3019.0,393.0,41523.0,7704.0,5413.0,906.0,83.0,3.0,782.0
8,20210307,DC,41419.0,10708.0,20164.0,914.0,86.0,8455.0,1030.0,105.0,773.0,14.0,NaN,119.0
9,20210307,DE,88354.0,42730.0,19768.0,1842.0,NaN,14532.0,1473.0,1036.0,329.0,11.0,NaN,80.0
10,20210307,FL,1944995.0,664121.0,237772.0,NaN,NaN,608165.0,32266.0,17316.0,4812.0,NaN,NaN,7325.0
11,20210307,GA,1023487.0,319208.0,216068.0,17888.0,504.0,85460.0,17906.0,8939.0,5282.0,298.0,10.0,852.0
12,20210307,GU,7749.0,418.0,NaN,2276.0,NaN,NaN,133.0,3.0,NaN,33.0,NaN,NaN
13,20210307,HI,27891.0,3646.0,580.0,6068.0,NaN,NaN,445.0,40.0,4.0,244.0,NaN,NaN
14,20210307,IA,339671.0,200406.0,10190.0,3397.0,888.0,20380.0,5558.0,5154.0,134.0,61.0,19.0,138.0
15,20210307,ID,172931.0,99914.0,1008.0,1219.0,2054.0,17344.0,1879.0,1761.0,9.0,17.0,35.0,186.0
16,20210307,IL,1198335.0,470333.0,110701.0,27074.0,1492.0,219967.0,23014.0,12202.0,3668.0,737.0,26.0,3291.0
17,20210307,IN,667262.0,452265.0,44471.0,8987.0,NaN,38378.0,12737.0,9096.0,939.0,70.0,NaN,275.0
18,20210307,KS,295861.0,209752.0,14330.0,5525.0,2074.0,39177.0,4812.0,3721.0,235.0,64.0,38.0,310.0
19,20210307,KY,410709.0,286431.0,26883.0,3680.0,833.0,17452.0,4819.0,3981.0,371.0,23.0,4.0,73.0
20,20210307,LA,433785.0,218332.0,136460.0,16684.0,1527.0,NaN,9748.0,5798.0,3723.0,75.0,15.0,238.0
21,20210307,MA,591356.0,219467.0,35342.0,16039.0,504.0,125873.0,16417.0,12022.0,1069.0,414.0,11.0,1289.0
22,20210307,MD,387319.0,134697.0,112033.0,8867.0,NaN,62261.0,7955.0,4078.0,2736.0,277.0,NaN,727.0
23,20210307,ME,45794.0,36271.0,2252.0,502.0,139.0,695.0,706.0,602.0,10.0,3.0,5.0,6.0
24,20210307,MI,656072.0,378135.0,74321.0,10362.0,3596.0,33855.0,16658.0,11205.0,3634.0,179.0,79.0,480.0
25,20210307,MN,490011.0,327714.0,39044.0,21470.0,4634.0,43792.0,6550.0,5440.0,319.0,259.0,90.0,203.0
26,20210307,MO,480643.0,252254.0,42276.0,4317.0,942.0,17167.0,8161.0,5162.0,1069.0,67.0,12.0,170.0
27,20210307,MP,145.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
28,20210307,MS,297581.0,140893.0,97848.0,1415.0,2215.0,6525.0,6808.0,3670.0,2671.0,18.0,114.0,60.0
29,20210307,MT,100914.0,63627.0,460.0,342.0,8156.0,2323.0,1381.0,856.0,1.0,1.0,205.0,25.0
30,20210307,NC,872176.0,442322.0,146993.0,13620.0,11199.0,118914.0,11502.0,7160.0,2662.0,120.0,126.0,803.0
31,20210307,ND,100391.0,55720.0,2881.0,1317.0,4376.0,NaN,1478.0,NaN,NaN,NaN,NaN,NaN
32,20210307,NE,201608.0,104512.0,5117.0,2809.0,1257.0,23560.0,2091.0,1360.0,58.0,30.0,26.0,161.0
33,20210307,NH,76861.0,39457.0,1025.0,1036.0,87.0,4157.0,1184.0,1110.0,13.0,12.0,1.0,30.0
34,20210307,NJ,812609.0,268537.0,69860.0,30370.0,NaN,161066.0,23574.0,12932.0,3743.0,1178.0,NaN,4338.0
35,20210307,NM,186922.0,32321.0,2360.0,1688.0,30459.0,87747.0,3808.0,1097.0,49.0,27.0,1064.0,1471.0
36,20210307,NV,296190.0,108109.0,22510.0,24287.0,1480.0,106628.0,5037.0,2719.0,468.0,594.0,45.0,1203.0
37,20210307,NY,1681169.0,NaN,NaN,NaN,NaN,NaN,48591.0,17007.0,9812.0,3011.0,NaN,9968.0
38,20210307,OH,978471.0,579544.0,101785.0,13511.0,1055.0,30674.0,17656.0,15026.0,2157.0,139.0,16.0,302.0
39,20210307,OK,428997.0,244180.0,23119.0,7852.0,41839.0,42955.0,4534.0,3255.0,271.0,57.0,399.0,232.0
40,20210307,OR,157285.0,76447.0,3791.0,4850.0,2769.0,40965.0,2296.0,1531.0,46.0,58.0,41.0,211.0
41,20210307,PA,948643.0,487131.0,81180.0,16176.0,NaN,59427.0,24349.0,19497.0,2829.0,379.0,NaN,982.0
42,20210307,PR,101327.0,NaN,NaN,NaN,NaN,NaN,2059.0,NaN,NaN,NaN,NaN,NaN
43,20210307,RI,128121.0,59389.0,7780.0,2342.0,309.0,31023.0,2541.0,1816.0,104.0,37.0,1.0,207.0
44,20210307,SC,525865.0,238659.0,107296.0,5178.0,NaN,29233.0,8754.0,4727.0,2408.0,54.0,NaN,211.0
45,20210307,SD,113589.0,84776.0,2519.0,1468.0,13518.0,4145.0,1900.0,1499.0,7.0,16.0,265.0,23.0
46,20210307,TN,783484.0,489782.0,102220.0,6937.0,1032.0,48832.0,11547.0,8730.0,1994.0,67.0,9.0,303.0
47,20210307,TX,2686818.0,25581.0,12672.0,933.0,NaN,27728.0,44451.0,18276.0,4252.0,898.0,NaN,20453.0
48,20210307,UT,374850.0,238411.0,5001.0,7107.0,5016.0,77215.0,1976.0,1329.0,18.0,59.0,72.0,282.0
49,20210307,VA,585700.0,235269.0,99166.0,19984.0,756.0,76875.0,9596.0,6002.0,2262.0,337.0,24.0,640.0
50,20210307,VI,2714.0,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN
51,20210307,VT,16083.0,12735.0,613.0,746.0,20.0,368.0,208.0,185.0,2.0,5.0,1.0,0.0
52,20210307,WA,344532.0,96572.0,10932.0,12525.0,3231.0,62537.0,5041.0,3571.0,161.0,383.0,107.0,596.0
53,20210307,WI,621654.0,481041.0,40549.0,15553.0,7580.0,63651.0,7106.0,6144.0,478.0,127.0,97.0,389.0
54,20210307,WV,133445.0,111202.0,4623.0,NaN,NaN,NaN,2325.0,2049.0,57.0,NaN,NaN,NaN
55,20210307,WY,54764.0,28117.0,425.0,281.0,2250.0,4134.0,682.0,606.0,2.0,6.0,51.0,58.0

In [4]:
# remove NAN

print(extractData.isnull().values.any())

cleanCOVIDdata = extractData.dropna()
print(cleanCOVIDdata.shape)

cleanCOVIDdata

True
(36, 14)

,Date,State,Cases_Total,Cases_White,Cases_Black,Cases_Asian,Cases_AIAN,Cases_Ethnicity_Hispanic,Deaths_Total,Deaths_White,Deaths_Black,Deaths_Asian,Deaths_AIAN,Deaths_Ethnicity_Hispanic
0,20210307,AK,59332.0,18300.0,1499.0,2447.0,12238.0,3197.0,305.0,127.0,9.0,29.0,111.0,13.0
2,20210307,AR,324818.0,207596.0,50842.0,2913.0,1070.0,34332.0,5319.0,4171.0,784.0,36.0,18.0,186.0
4,20210307,AZ,826454.0,308453.0,25775.0,11921.0,40707.0,244539.0,16328.0,8066.0,433.0,220.0,1361.0,4684.0
5,20210307,CA,3501394.0,546630.0,111279.0,186562.0,9025.0,1509103.0,54124.0,16586.0,3275.0,6105.0,184.0,24402.0
6,20210307,CO,435762.0,181669.0,12637.0,6406.0,2527.0,119224.0,5986.0,3869.0,191.0,115.0,37.0,1204.0
7,20210307,CT,285330.0,85469.0,19651.0,3019.0,393.0,41523.0,7704.0,5413.0,906.0,83.0,3.0,782.0
11,20210307,GA,1023487.0,319208.0,216068.0,17888.0,504.0,85460.0,17906.0,8939.0,5282.0,298.0,10.0,852.0
14,20210307,IA,339671.0,200406.0,10190.0,3397.0,888.0,20380.0,5558.0,5154.0,134.0,61.0,19.0,138.0
15,20210307,ID,172931.0,99914.0,1008.0,1219.0,2054.0,17344.0,1879.0,1761.0,9.0,17.0,35.0,186.0
16,20210307,IL,1198335.0,470333.0,110701.0,27074.0,1492.0,219967.0,23014.0,12202.0,3668.0,737.0,26.0,3291.0
18,20210307,KS,295861.0,209752.0,14330.0,5525.0,2074.0,39177.0,4812.0,3721.0,235.0,64.0,38.0,310.0
19,20210307,KY,410709.0,286431.0,26883.0,3680.0,833.0,17452.0,4819.0,3981.0,371.0,23.0,4.0,73.0
21,20210307,MA,591356.0,219467.0,35342.0,16039.0,504.0,125873.0,16417.0,12022.0,1069.0,414.0,11.0,1289.0
23,20210307,ME,45794.0,36271.0,2252.0,502.0,139.0,695.0,706.0,602.0,10.0,3.0,5.0,6.0
24,20210307,MI,656072.0,378135.0,74321.0,10362.0,3596.0,33855.0,16658.0,11205.0,3634.0,179.0,79.0,480.0
25,20210307,MN,490011.0,327714.0,39044.0,21470.0,4634.0,43792.0,6550.0,5440.0,319.0,259.0,90.0,203.0
26,20210307,MO,480643.0,252254.0,42276.0,4317.0,942.0,17167.0,8161.0,5162.0,1069.0,67.0,12.0,170.0
28,20210307,MS,297581.0,140893.0,97848.0,1415.0,2215.0,6525.0,6808.0,3670.0,2671.0,18.0,114.0,60.0
29,20210307,MT,100914.0,63627.0,460.0,342.0,8156.0,2323.0,1381.0,856.0,1.0,1.0,205.0,25.0
30,20210307,NC,872176.0,442322.0,146993.0,13620.0,11199.0,118914.0,11502.0,7160.0,2662.0,120.0,126.0,803.0
32,20210307,NE,201608.0,104512.0,5117.0,2809.0,1257.0,23560.0,2091.0,1360.0,58.0,30.0,26.0,161.0
33,20210307,NH,76861.0,39457.0,1025.0,1036.0,87.0,4157.0,1184.0,1110.0,13.0,12.0,1.0,30.0
35,20210307,NM,186922.0,32321.0,2360.0,1688.0,30459.0,87747.0,3808.0,1097.0,49.0,27.0,1064.0,1471.0
36,20210307,NV,296190.0,108109.0,22510.0,24287.0,1480.0,106628.0,5037.0,2719.0,468.0,594.0,45.0,1203.0
38,20210307,OH,978471.0,579544.0,101785.0,13511.0,1055.0,30674.0,17656.0,15026.0,2157.0,139.0,16.0,302.0
39,20210307,OK,428997.0,244180.0,23119.0,7852.0,41839.0,42955.0,4534.0,3255.0,271.0,57.0,399.0,232.0
40,20210307,OR,157285.0,76447.0,3791.0,4850.0,2769.0,40965.0,2296.0,1531.0,46.0,58.0,41.0,211.0
43,20210307,RI,128121.0,59389.0,7780.0,2342.0,309.0,31023.0,2541.0,1816.0,104.0,37.0,1.0,207.0
45,20210307,SD,113589.0,84776.0,2519.0,1468.0,13518.0,4145.0,1900.0,1499.0,7.0,16.0,265.0,23.0
46,20210307,TN,783484.0,489782.0,102220.0,6937.0,1032.0,48832.0,11547.0,8730.0,1994.0,67.0,9.0,303.0
48,20210307,UT,374850.0,238411.0,5001.0,7107.0,5016.0,77215.0,1976.0,1329.0,18.0,59.0,72.0,282.0
49,20210307,VA,585700.0,235269.0,99166.0,19984.0,756.0,76875.0,9596.0,6002.0,2262.0,337.0,24.0,640.0
51,20210307,VT,16083.0,12735.0,613.0,746.0,20.0,368.0,208.0,185.0,2.0,5.0,1.0,0.0
52,20210307,WA,344532.0,96572.0,10932.0,12525.0,3231.0,62537.0,5041.0,3571.0,161.0,383.0,107.0,596.0
53,20210307,WI,621654.0,481041.0,40549.0,15553.0,7580.0,63651.0,7106.0,6144.0,478.0,127.0,97.0,389.0
55,20210307,WY,54764.0,28117.0,425.0,281.0,2250.0,4134.0,682.0,606.0,2.0,6.0,51.0,58.0

In [5]:
# Data for population for different ethnic group for each state

popData = pd.read_csv('populationbyRace2019.csv')
popData

,Location,State,White,Black,Hispanic,Asian,Indian,Native Hawaiian/Other Pacific Islander,Multiple Races,Total
0,United States,United States,191757100,38872200,59102900,18007200.0,2125700.0,528200.0,8856100,319249300
1,Alabama,AL,3117200,1263500,211700,65200.0,18800.0,NaN,89200,4767100
2,Alaska,AK,421100,15200,48900,42000.0,106000.0,10400.0,58200,701700
3,Arizona,AZ,3843700,306600,2254800,231000.0,276100.0,12500.0,173400,7098000
4,Arkansas,AR,2108400,444200,226800,45500.0,16700.0,10800.0,70100,2922500
5,California,CA,14047400,2066300,15271400,5691100.0,138800.0,137000.0,1290700,38642700
6,Colorado,CO,3804100,211100,1221900,180300.0,29400.0,6200.0,158700,5611800
7,Connecticut,CT,2268200,346400,583300,158600.0,5600.0,NaN,90100,3453300
8,Delaware,DE,577700,205100,91100,36900.0,3000.0,NaN,26300,940300
9,District of Columbia,DC,246100,302400,75200,25200.0,1800.0,NaN,20500,671300
10,Florida,FL,11119200,3150100,5583900,573500.0,39900.0,12200.0,513300,20992000
11,Georgia,GA,5354500,3225900,1011800,422400.0,19700.0,5800.0,253900,10294000
12,Hawaii,HI,274400,16400,137900,528600.0,1600.0,136900.0,247200,1343000
13,Idaho,ID,1429500,11500,225600,21600.0,15900.0,NaN,44800,1750900
14,Illinois,IL,7522700,1679900,2177500,695500.0,11300.0,3000.0,272500,12362300
15,Indiana,IN,5116000,600500,471000,158800.0,12300.0,NaN,151300,6511800
16,Iowa,IA,2610600,119200,191600,71600.0,8800.0,1000.0,57400,3060200
17,Kansas,KS,2128700,153300,341900,79900.0,17500.0,NaN,89100,2811200
18,Kentucky,KY,3648500,344900,160800,70400.0,4900.0,NaN,87500,4319300
19,Louisiana,LA,2643900,1433000,235800,76600.0,21600.0,NaN,86900,4498600
20,Maine,ME,1213500,17800,21900,14500.0,9700.0,NaN,24600,1302300
21,Maryland,MD,2934100,1741500,624500,373300.0,12400.0,NaN,188100,5875500
22,Massachusetts,MA,4687000,466200,824100,448000.0,12000.0,2600.0,210800,6650800
23,Michigan,MI,7316400,1305100,514600,315900.0,47100.0,NaN,264900,9765600
24,Minnesota,MN,4361600,353700,307300,272500.0,50900.0,NaN,165900,5514800
25,Mississippi,MS,1622400,1078300,85900,28600.0,11000.0,NaN,40700,2867100
26,Missouri,MO,4715000,667100,253900,122500.0,21200.0,8200.0,152000,5939900
27,Montana,MT,895200,5900,38300,7900.0,62900.0,NaN,28700,1039400
28,Nebraska,NE,1470900,89200,212200,45200.0,14800.0,NaN,40200,1873600
29,Nevada,NV,1448800,279000,888400,257500.0,26700.0,17500.0,111900,3029700
30,New Hampshire,NH,1179700,17600,51500,34800.0,NaN,NaN,27600,1314000
31,New Jersey,NJ,4738500,1081400,1822900,836400.0,8800.0,NaN,209000,8699400
32,New Mexico,NM,750000,35000,1010200,32900.0,176600.0,NaN,36000,2041400
33,New York,NY,10432200,2651600,3649800,1625500.0,39100.0,NaN,507900,18908300
34,North Carolina,NC,6355400,2124200,987900,294400.0,112600.0,4800.0,260600,10139700
35,North Dakota,ND,614600,17900,29400,10400.0,38000.0,NaN,19100,731000
36,Ohio,OH,8918300,1380000,452300,260500.0,15800.0,NaN,321400,11351500
37,Oklahoma,OK,2488200,262800,424600,78900.0,295000.0,4600.0,272800,3826900
38,Oregon,OR,3097700,72900,553400,192000.0,38900.0,10900.0,163100,4128900
39,Pennsylvania,PA,9401500,1282000,960500,438000.0,14200.0,2300.0,279200,12377600
40,Rhode Island,RI,717300,60300,169100,34000.0,2300.0,NaN,33900,1017100
41,South Carolina,SC,3177000,1307200,285200,84100.0,14300.0,NaN,108300,4984200
42,South Dakota,SD,697500,18800,31400,11000.0,71500.0,NaN,20500,851300
43,Tennessee,TN,4884500,1088500,378900,120600.0,17200.0,NaN,148700,6640900
44,Texas,TX,11637100,3297200,11300500,1409700.0,76800.0,19000.0,545800,28286200
45,Utah,UT,2452300,32600,455000,72800.0,31100.0,25800.0,84400,3154100
46,Vermont,VT,555100,6700,10600,9700.0,4000.0,NaN,11900,598100
47,Virginia,VA,5017100,1543100,787100,551900.0,13600.0,3900.0,268300,8185100
48,Washington,WA,5013200,282700,964700,662400.0,82400.0,47400.0,371100,7423900
49,West Virginia,WV,1609000,55900,24800,14200.0,3900.0,NaN,31200,1739000
50,Wisconsin,WI,4602500,349200,401700,169100.0,37400.0,NaN,114100,5677100
51,Wyoming,WY,471600,5400,57100,3400.0,12300.0,NaN,12000,562700
52,Puerto Rico,PR,42600,3100,3106600,NaN,NaN,NaN,9100,3164500

In [6]:
# total number of states in COVID data, some states are removed because of NAN
n_states = len(cleanCOVIDdata.iloc[:,1])
print(n_states)

#total states in population file
p_states = len(popData.iloc[:,0])
print(p_states)
     
R_cases_total = []
R_cases_white = []
R_cases_black = []
R_cases_hispanic = []
R_cases_asian = []
R_cases_indian = []

R_deaths_total = []
R_deaths_white = []
R_deaths_black = []
R_deaths_hispanic = []
R_deaths_asian = []
R_deaths_indian = []

# store ratios for each state
Ratios = pd.DataFrame()


for s in range(n_states):
    state_in_COVID = cleanCOVIDdata.iloc[s,]
   
    for p in range(p_states):
        state_in_pop = popData.iloc[p,]
        
        if state_in_COVID['State'] == state_in_pop['State']:
            r_t = state_in_COVID['Cases_Total'] / state_in_pop['Total']
            r_t = round(r_t, 3)
            R_cases_total.append(r_t)
            
            r_w = state_in_COVID['Cases_White'] / state_in_pop['White']
            r_w = round(r_w, 3)
            R_cases_white.append(r_w)
            
            r_b = state_in_COVID['Cases_Black'] / state_in_pop['Black']
            r_b = round(r_b, 3)
            R_cases_black.append(r_b)
            
            r_h = state_in_COVID['Cases_Ethnicity_Hispanic'] / state_in_pop['Hispanic']
            r_h = round(r_h, 3)
            R_cases_hispanic.append(r_h)
            
            r_a = state_in_COVID['Cases_Asian'] / state_in_pop['Asian']
            r_a = round(r_a, 3)
            R_cases_asian.append(r_a)
            
            r_i = state_in_COVID['Cases_AIAN'] / state_in_pop['Indian']
            r_i = round(r_i, 3)
            R_cases_indian.append(r_i)
            
            
            r_d_t = state_in_COVID['Deaths_Total'] / state_in_pop['Total']
            r_d_t = round(r_d_t, 5)
            R_deaths_total.append(r_d_t)
            
            r_d_w = state_in_COVID['Deaths_White'] / state_in_pop['White']
            r_d_w = round(r_d_w, 5)
            R_deaths_white.append(r_d_w)
            
            r_d_b = state_in_COVID['Deaths_Black'] / state_in_pop['Black']
            r_d_b = round(r_d_b, 5)
            R_deaths_black.append(r_d_b)
            
            r_d_h = state_in_COVID['Deaths_Ethnicity_Hispanic'] / state_in_pop['Hispanic']
            r_d_h = round(r_d_h, 5)
            R_deaths_hispanic.append(r_d_h)
            
            r_d_a = state_in_COVID['Deaths_Asian'] / state_in_pop['Asian']
            r_d_a = round(r_d_a, 5)
            R_deaths_asian.append(r_d_a)
            
            r_d_i = state_in_COVID['Deaths_AIAN'] / state_in_pop['Indian']
            r_d_i = round(r_d_i, 5)
            R_deaths_indian.append(r_d_i)
                    
            continue

            
Ratios['State'] = cleanCOVIDdata.iloc[:, 1]
Ratios['case_Total'] = R_cases_total
Ratios['case_White'] = R_cases_white
Ratios['case_Black'] = R_cases_black
Ratios['case_Hispanic'] = R_cases_hispanic
Ratios['case_Asian'] = R_cases_asian
Ratios['case_Indian'] = R_cases_indian

Ratios['death_Total'] = R_deaths_total
Ratios['death_White'] = R_deaths_white
Ratios['death_Black'] = R_deaths_black
Ratios['death_Hispanic'] = R_deaths_hispanic
Ratios['death_Asian'] = R_deaths_asian
Ratios['death_Indian'] = R_deaths_indian
Ratios

36
53

,State,case_Total,case_White,case_Black,case_Hispanic,case_Asian,case_Indian,death_Total,death_White,death_Black,death_Hispanic,death_Asian,death_Indian
0,AK,0.085,0.043,0.099,0.065,0.058,0.115,0.00043,0.00030,0.00059,0.00027,0.00069,0.00105
2,AR,0.111,0.098,0.114,0.151,0.064,0.064,0.00182,0.00198,0.00176,0.00082,0.00079,0.00108
4,AZ,0.116,0.080,0.084,0.108,0.052,0.147,0.00230,0.00210,0.00141,0.00208,0.00095,0.00493
5,CA,0.091,0.039,0.054,0.099,0.033,0.065,0.00140,0.00118,0.00158,0.00160,0.00107,0.00133
6,CO,0.078,0.048,0.060,0.098,0.036,0.086,0.00107,0.00102,0.00090,0.00099,0.00064,0.00126
7,CT,0.083,0.038,0.057,0.071,0.019,0.070,0.00223,0.00239,0.00262,0.00134,0.00052,0.00054
11,GA,0.099,0.060,0.067,0.084,0.042,0.026,0.00174,0.00167,0.00164,0.00084,0.00071,0.00051
14,IA,0.111,0.077,0.085,0.106,0.047,0.101,0.00182,0.00197,0.00112,0.00072,0.00085,0.00216
15,ID,0.099,0.070,0.088,0.077,0.056,0.129,0.00107,0.00123,0.00078,0.00082,0.00079,0.00220
16,IL,0.097,0.063,0.066,0.101,0.039,0.132,0.00186,0.00162,0.00218,0.00151,0.00106,0.00230
18,KS,0.105,0.099,0.093,0.115,0.069,0.119,0.00171,0.00175,0.00153,0.00091,0.00080,0.00217
19,KY,0.095,0.079,0.078,0.109,0.052,0.170,0.00112,0.00109,0.00108,0.00045,0.00033,0.00082
21,MA,0.089,0.047,0.076,0.153,0.036,0.042,0.00247,0.00256,0.00229,0.00156,0.00092,0.00092
23,ME,0.035,0.030,0.127,0.032,0.035,0.014,0.00054,0.00050,0.00056,0.00027,0.00021,0.00052
24,MI,0.067,0.052,0.057,0.066,0.033,0.076,0.00171,0.00153,0.00278,0.00093,0.00057,0.00168
25,MN,0.089,0.075,0.110,0.143,0.079,0.091,0.00119,0.00125,0.00090,0.00066,0.00095,0.00177
26,MO,0.081,0.054,0.063,0.068,0.035,0.044,0.00137,0.00109,0.00160,0.00067,0.00055,0.00057
28,MS,0.104,0.087,0.091,0.076,0.049,0.201,0.00237,0.00226,0.00248,0.00070,0.00063,0.01036
29,MT,0.097,0.071,0.078,0.061,0.043,0.130,0.00133,0.00096,0.00017,0.00065,0.00013,0.00326
30,NC,0.086,0.070,0.069,0.120,0.046,0.099,0.00113,0.00113,0.00125,0.00081,0.00041,0.00112
32,NE,0.108,0.071,0.057,0.111,0.062,0.085,0.00112,0.00092,0.00065,0.00076,0.00066,0.00176
33,NH,0.058,0.033,0.058,0.081,0.030,NaN,0.00090,0.00094,0.00074,0.00058,0.00034,NaN
35,NM,0.092,0.043,0.067,0.087,0.051,0.172,0.00187,0.00146,0.00140,0.00146,0.00082,0.00602
36,NV,0.098,0.075,0.081,0.120,0.094,0.055,0.00166,0.00188,0.00168,0.00135,0.00231,0.00169
38,OH,0.086,0.065,0.074,0.068,0.052,0.067,0.00156,0.00168,0.00156,0.00067,0.00053,0.00101
39,OK,0.112,0.098,0.088,0.101,0.100,0.142,0.00118,0.00131,0.00103,0.00055,0.00072,0.00135
40,OR,0.038,0.025,0.052,0.074,0.025,0.071,0.00056,0.00049,0.00063,0.00038,0.00030,0.00105
43,RI,0.126,0.083,0.129,0.183,0.069,0.134,0.00250,0.00253,0.00172,0.00122,0.00109,0.00043
45,SD,0.133,0.122,0.134,0.132,0.133,0.189,0.00223,0.00215,0.00037,0.00073,0.00145,0.00371
46,TN,0.118,0.100,0.094,0.129,0.058,0.060,0.00174,0.00179,0.00183,0.00080,0.00056,0.00052
48,UT,0.119,0.097,0.153,0.170,0.098,0.161,0.00063,0.00054,0.00055,0.00062,0.00081,0.00232
49,VA,0.072,0.047,0.064,0.098,0.036,0.056,0.00117,0.00120,0.00147,0.00081,0.00061,0.00176
51,VT,0.027,0.023,0.091,0.035,0.077,0.005,0.00035,0.00033,0.00030,0.00000,0.00052,0.00025
52,WA,0.046,0.019,0.039,0.065,0.019,0.039,0.00068,0.00071,0.00057,0.00062,0.00058,0.00130
53,WI,0.110,0.105,0.116,0.158,0.092,0.203,0.00125,0.00133,0.00137,0.00097,0.00075,0.00259
55,WY,0.097,0.060,0.079,0.072,0.083,0.183,0.00121,0.00128,0.00037,0.00102,0.00176,0.00415

In [7]:
# expert dataframe to csv file

Ratios.to_csv('COVID_CasesDeathsRatios_byRaceState.csv')